deps:
	go get -u github.com/libp2p/go-libp2p
	go get -u github.com/libp2p/go-floodsub
	go get -u github.com/libp2p/go-libp2p-kad-dht
	go get -u github.com/multiformats/go-multiaddr
	go get -u github.com/ipfs/go-ipfs-addr
	go get -u github.com/OpenBazaar/go-onion-transport
	go get -u github.com/OpenBazaar/openbazaar-go/net

build:
	go build -o libp2p-demo *.go

clean:
	rm libp2p-demo
